import type { Node } from "../menu";

const installBrowser: Node = {
  type: "group",
  id: "install-browser",
  title: "Browser",
  icon: "browser",
  children: [
    {
      type: "cmd",
      id: "install-browser-chrome",
      title: "Chrome",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-browser", "chrome"],
    },
    {
      type: "cmd",
      id: "install-browser-edge",
      title: "Edge",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-browser", "edge"],
    },
    {
      type: "cmd",
      id: "install-browser-brave",
      title: "Brave",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-browser", "brave"],
    },
    {
      type: "cmd",
      id: "install-browser-brave-origin",
      title: "Brave Origin",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-browser", "brave-origin"],
    },
    {
      type: "cmd",
      id: "install-browser-firefox",
      title: "Firefox",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-browser", "firefox"],
    },
    {
      type: "cmd",
      id: "install-browser-zen",
      title: "Zen",
      icon: "globe-hemisphere-west",
      terminal: true,
      exec: ["maitri-install-browser", "zen"],
    },
  ],
};

const installService: Node = {
  type: "group",
  id: "install-service",
  title: "Service",
  icon: "cloud",
  children: [
    {
      type: "cmd",
      id: "install-service-dropbox",
      title: "Dropbox",
      icon: "dropbox-logo",
      terminal: true,
      exec: ["maitri-install-dropbox"],
    },
    {
      type: "cmd",
      id: "install-service-tailscale",
      title: "Tailscale",
      icon: "shield",
      terminal: true,
      exec: ["maitri-install-tailscale"],
    },
    {
      type: "cmd",
      id: "install-service-nordvpn",
      title: "NordVPN [AUR]",
      icon: "shield-check",
      terminal: true,
      exec: ["maitri-install-nordvpn"],
    },
    {
      type: "cmd",
      id: "install-service-once",
      title: "ONCE",
      icon: "package",
      terminal: true,
      exec: ["maitri-install-once"],
    },
    {
      type: "cmd",
      id: "install-service-bitwarden",
      title: "Bitwarden",
      icon: "vault",
      terminal: true,
      exec: ["maitri-pkg-add", "bitwarden", "bitwarden-cli"],
    },
    {
      type: "cmd",
      id: "install-service-chromium-account",
      title: "Chromium Account",
      icon: "globe",
      terminal: true,
      exec: ["maitri-install-chromium-google-account"],
    },
  ],
};

const installEditor: Node = {
  type: "group",
  id: "install-editor",
  title: "Editor",
  icon: "pencil-simple",
  children: [
    {
      type: "cmd",
      id: "install-editor-vscode",
      title: "VSCode",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-vscode"],
    },
    {
      type: "cmd",
      id: "install-editor-cursor",
      title: "Cursor",
      icon: "code",
      terminal: true,
      exec: ["maitri-pkg-add", "cursor-bin"],
    },
    {
      type: "cmd",
      id: "install-editor-zed",
      title: "Zed",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-zed"],
    },
    {
      type: "cmd",
      id: "install-editor-sublime",
      title: "Sublime Text",
      icon: "code",
      terminal: true,
      exec: ["maitri-pkg-add", "sublime-text-4"],
    },
    {
      type: "cmd",
      id: "install-editor-helix",
      title: "Helix",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-helix"],
    },
    {
      type: "cmd",
      id: "install-editor-vim",
      title: "Vim",
      icon: "code",
      terminal: true,
      exec: ["maitri-pkg-add", "vim"],
    },
    {
      type: "cmd",
      id: "install-editor-emacs",
      title: "Emacs",
      icon: "code",
      terminal: true,
      exec: ["maitri-pkg-add", "emacs-wayland"],
    },
  ],
};

const installTerminal: Node = {
  type: "group",
  id: "install-terminal",
  title: "Terminal",
  icon: "terminal-window",
  children: [
    {
      type: "cmd",
      id: "install-terminal-alacritty",
      title: "Alacritty",
      icon: "terminal",
      terminal: true,
      exec: ["maitri-install-terminal", "alacritty"],
    },
    {
      type: "cmd",
      id: "install-terminal-foot",
      title: "Foot",
      icon: "terminal",
      terminal: true,
      exec: ["maitri-install-terminal", "foot"],
    },
    {
      type: "cmd",
      id: "install-terminal-ghostty",
      title: "Ghostty",
      icon: "terminal",
      terminal: true,
      exec: ["maitri-install-terminal", "ghostty"],
    },
    {
      type: "cmd",
      id: "install-terminal-kitty",
      title: "Kitty",
      icon: "terminal",
      terminal: true,
      exec: ["maitri-install-terminal", "kitty"],
    },
  ],
};

const installAi: Node = {
  type: "group",
  id: "install-ai",
  title: "AI",
  icon: "robot",
  children: [
    {
      type: "cmd",
      id: "install-ai-dictation",
      title: "Dictation",
      icon: "microphone",
      terminal: true,
      exec: ["maitri-voxtype-install"],
    },
    {
      type: "cmd",
      id: "install-ai-lm-studio",
      title: "LM Studio",
      icon: "robot",
      terminal: true,
      exec: ["maitri-pkg-add", "lmstudio-bin"],
    },
    {
      type: "cmd",
      id: "install-ai-ollama",
      title: "Ollama",
      icon: "robot",
      terminal: true,
      exec: ["maitri-pkg-add", "ollama"],
    },
    {
      type: "cmd",
      id: "install-ai-crush",
      title: "Crush",
      icon: "robot",
      terminal: true,
      exec: ["maitri-pkg-add", "crush-bin"],
    },
  ],
};

const installGaming: Node = {
  type: "group",
  id: "install-gaming",
  title: "Gaming",
  icon: "game-controller",
  children: [
    {
      type: "cmd",
      id: "install-gaming-steam",
      title: "Steam",
      icon: "game-controller",
      terminal: true,
      exec: ["maitri-install-gaming-steam"],
    },
    {
      type: "cmd",
      id: "install-gaming-retroarch",
      title: "RetroArch",
      icon: "joystick",
      terminal: true,
      exec: ["maitri-install-gaming-retroarch"],
    },
    {
      type: "cmd",
      id: "install-gaming-minecraft",
      title: "Minecraft",
      icon: "cube",
      terminal: true,
      exec: ["maitri-pkg-add", "minecraft-launcher"],
    },
    {
      type: "cmd",
      id: "install-gaming-geforce-now",
      title: "NVIDIA GeForce NOW",
      icon: "monitor-play",
      terminal: true,
      exec: ["maitri-install-gaming-geforce-now"],
    },
    {
      type: "cmd",
      id: "install-gaming-xbox-cloud",
      title: "Xbox Cloud Gaming",
      icon: "cloud",
      terminal: true,
      exec: ["maitri-install-gaming-xbox-cloud"],
    },
    {
      type: "cmd",
      id: "install-gaming-xbox-controller",
      title: "Xbox Controller",
      icon: "game-controller",
      terminal: true,
      exec: ["maitri-install-gaming-xbox-controllers"],
    },
    {
      type: "cmd",
      id: "install-gaming-moonlight",
      title: "Moonlight (GameStream)",
      icon: "monitor",
      terminal: true,
      exec: ["maitri-install-gaming-moonlight"],
    },
    {
      type: "cmd",
      id: "install-gaming-lutris",
      title: "Lutris (Battle.net)",
      icon: "game-controller",
      terminal: true,
      exec: ["maitri-install-gaming-lutris"],
    },
    {
      type: "cmd",
      id: "install-gaming-heroic",
      title: "Heroic (Epic Games)",
      icon: "game-controller",
      terminal: true,
      exec: ["maitri-install-gaming-heroic"],
    },
  ],
};

const installFont: Node = {
  type: "group",
  id: "install-font",
  title: "Font",
  icon: "text-aa",
  children: [
    {
      type: "cmd",
      id: "install-font-cascadia-mono",
      title: "Cascadia Mono",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-cascadia-mono-nerd"],
    },
    {
      type: "cmd",
      id: "install-font-meslo-lg-mono",
      title: "Meslo LG Mono",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-meslo-nerd"],
    },
    {
      type: "cmd",
      id: "install-font-fira-code",
      title: "Fira Code",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-firacode-nerd"],
    },
    {
      type: "cmd",
      id: "install-font-victor-code",
      title: "Victor Code",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-victor-mono-nerd"],
    },
    {
      type: "cmd",
      id: "install-font-bitstream-vera-mono",
      title: "Bitstream Vera Mono",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-bitstream-vera-mono-nerd"],
    },
    {
      type: "cmd",
      id: "install-font-iosevka",
      title: "Iosevka",
      icon: "text-aa",
      terminal: true,
      exec: ["maitri-pkg-add", "ttf-iosevka-nerd"],
    },
  ],
};

const installStyle: Node = {
  type: "group",
  id: "install-style",
  title: "Style",
  icon: "paint-brush",
  children: [
    {
      type: "cmd",
      id: "install-style-theme",
      title: "Theme",
      icon: "palette",
      terminal: true,
      exec: ["maitri-theme-install"],
    },
    {
      type: "cmd",
      id: "install-style-background",
      title: "Background",
      icon: "image",
      exec: ["maitri-theme-bg-install"],
    },
    installFont,
  ],
};

const installJavascript: Node = {
  type: "group",
  id: "install-javascript",
  title: "JavaScript",
  icon: "code",
  children: [
    {
      type: "cmd",
      id: "install-javascript-node",
      title: "Node.js",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "node"],
    },
    {
      type: "cmd",
      id: "install-javascript-bun",
      title: "Bun",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "bun"],
    },
    {
      type: "cmd",
      id: "install-javascript-deno",
      title: "Deno",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "deno"],
    },
  ],
};

const installPhp: Node = {
  type: "group",
  id: "install-php",
  title: "PHP",
  icon: "code",
  children: [
    {
      type: "cmd",
      id: "install-php-php",
      title: "PHP",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "php"],
    },
    {
      type: "cmd",
      id: "install-php-laravel",
      title: "Laravel",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "laravel"],
    },
    {
      type: "cmd",
      id: "install-php-symfony",
      title: "Symfony",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "symfony"],
    },
  ],
};

const installElixir: Node = {
  type: "group",
  id: "install-elixir",
  title: "Elixir",
  icon: "drop",
  children: [
    {
      type: "cmd",
      id: "install-elixir-elixir",
      title: "Elixir",
      icon: "drop",
      terminal: true,
      exec: ["maitri-install-dev-env", "elixir"],
    },
    {
      type: "cmd",
      id: "install-elixir-phoenix",
      title: "Phoenix",
      icon: "fire-simple",
      terminal: true,
      exec: ["maitri-install-dev-env", "phoenix"],
    },
  ],
};

const installDevelopment: Node = {
  type: "group",
  id: "install-development",
  title: "Development",
  icon: "wrench",
  children: [
    {
      type: "cmd",
      id: "install-development-rails",
      title: "Ruby on Rails",
      icon: "diamond",
      terminal: true,
      exec: ["maitri-install-dev-env", "ruby"],
    },
    {
      type: "cmd",
      id: "install-development-docker-db",
      title: "Docker DB",
      icon: "database",
      terminal: true,
      exec: ["maitri-install-docker-dbs"],
    },
    installJavascript,
    {
      type: "cmd",
      id: "install-development-go",
      title: "Go",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "go"],
    },
    installPhp,
    {
      type: "cmd",
      id: "install-development-python",
      title: "Python",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "python"],
    },
    installElixir,
    {
      type: "cmd",
      id: "install-development-zig",
      title: "Zig",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "zig"],
    },
    {
      type: "cmd",
      id: "install-development-rust",
      title: "Rust",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "rust"],
    },
    {
      type: "cmd",
      id: "install-development-java",
      title: "Java",
      icon: "coffee",
      terminal: true,
      exec: ["maitri-install-dev-env", "java"],
    },
    {
      type: "cmd",
      id: "install-development-dotnet",
      title: ".NET",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "dotnet"],
    },
    {
      type: "cmd",
      id: "install-development-ocaml",
      title: "OCaml",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "ocaml"],
    },
    {
      type: "cmd",
      id: "install-development-clojure",
      title: "Clojure",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "clojure"],
    },
    {
      type: "cmd",
      id: "install-development-scala",
      title: "Scala",
      icon: "code",
      terminal: true,
      exec: ["maitri-install-dev-env", "scala"],
    },
  ],
};

export const install: Node[] = [
  {
    type: "cmd",
    id: "install-package",
    title: "Package",
    icon: "package",
    terminal: true,
    exec: ["maitri-pkg-install"],
  },
  {
    type: "cmd",
    id: "install-aur",
    title: "AUR",
    icon: "package",
    terminal: true,
    exec: ["maitri-pkg-aur-install"],
  },
  {
    type: "cmd",
    id: "install-webapp",
    title: "Web App",
    icon: "app-window",
    terminal: true,
    exec: ["maitri-webapp-install"],
  },
  {
    type: "cmd",
    id: "install-tui",
    title: "TUI",
    icon: "terminal-window",
    terminal: true,
    exec: ["maitri-tui-install"],
  },
  installService,
  installStyle,
  installDevelopment,
  installEditor,
  installTerminal,
  installBrowser,
  installAi,
  installGaming,
  {
    type: "cmd",
    id: "install-windows",
    title: "Windows",
    icon: "windows-logo",
    terminal: true,
    exec: ["maitri-windows-vm", "install"],
  },
];
