import type { Node } from "../menu";

export const remove: Node[] = [
  {
    type: "group",
    id: "rm-menu",
    title: "Remove",
    icon: "minus-circle",
    children: [
      {
        type: "cmd",
        id: "rm-package",
        title: "Package",
        icon: "package",
        exec: ["maitri-pkg-remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Package?" },
      },
      {
        type: "cmd",
        id: "rm-webapp",
        title: "Web App",
        icon: "globe",
        exec: ["maitri-webapp-remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Web App?" },
      },
      {
        type: "cmd",
        id: "rm-tui",
        title: "TUI",
        icon: "terminal-window",
        exec: ["maitri-tui-remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove TUI?" },
      },
      {
        type: "group",
        id: "rm-development",
        title: "Development",
        icon: "code",
        children: [
          {
            type: "cmd",
            id: "rm-dev-rails",
            title: "Ruby on Rails",
            icon: "diamond",
            exec: ["maitri-remove-dev-env", "ruby"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Ruby on Rails?" },
          },
          {
            type: "group",
            id: "rm-dev-javascript",
            title: "JavaScript",
            icon: "file-js",
            children: [
              {
                type: "cmd",
                id: "rm-js-node",
                title: "Node.js",
                icon: "file-js",
                exec: ["maitri-remove-dev-env", "node"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Node.js?" },
              },
              {
                type: "cmd",
                id: "rm-js-bun",
                title: "Bun",
                icon: "file-js",
                exec: ["maitri-remove-dev-env", "bun"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Bun?" },
              },
              {
                type: "cmd",
                id: "rm-js-deno",
                title: "Deno",
                icon: "file-js",
                exec: ["maitri-remove-dev-env", "deno"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Deno?" },
              },
            ],
          },
          {
            type: "cmd",
            id: "rm-dev-go",
            title: "Go",
            icon: "code-block",
            exec: ["maitri-remove-dev-env", "go"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Go?" },
          },
          {
            type: "group",
            id: "rm-dev-php",
            title: "PHP",
            icon: "code-block",
            children: [
              {
                type: "cmd",
                id: "rm-php-php",
                title: "PHP",
                icon: "code-block",
                exec: ["maitri-remove-dev-env", "php"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove PHP?" },
              },
              {
                type: "cmd",
                id: "rm-php-laravel",
                title: "Laravel",
                icon: "code-block",
                exec: ["maitri-remove-dev-env", "laravel"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Laravel?" },
              },
              {
                type: "cmd",
                id: "rm-php-symfony",
                title: "Symfony",
                icon: "code-block",
                exec: ["maitri-remove-dev-env", "symfony"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Symfony?" },
              },
            ],
          },
          {
            type: "cmd",
            id: "rm-dev-python",
            title: "Python",
            icon: "code-block",
            exec: ["maitri-remove-dev-env", "python"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Python?" },
          },
          {
            type: "group",
            id: "rm-dev-elixir",
            title: "Elixir",
            icon: "drop",
            children: [
              {
                type: "cmd",
                id: "rm-elixir-elixir",
                title: "Elixir",
                icon: "drop",
                exec: ["maitri-remove-dev-env", "elixir"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Elixir?" },
              },
              {
                type: "cmd",
                id: "rm-elixir-phoenix",
                title: "Phoenix",
                icon: "bird",
                exec: ["maitri-remove-dev-env", "phoenix"],
                terminal: true,
                destructive: true,
                confirm: { title: "Remove Phoenix?" },
              },
            ],
          },
          {
            type: "cmd",
            id: "rm-dev-zig",
            title: "Zig",
            icon: "lightning",
            exec: ["maitri-remove-dev-env", "zig"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Zig?" },
          },
          {
            type: "cmd",
            id: "rm-dev-rust",
            title: "Rust",
            icon: "gear",
            exec: ["maitri-remove-dev-env", "rust"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Rust?" },
          },
          {
            type: "cmd",
            id: "rm-dev-java",
            title: "Java",
            icon: "coffee",
            exec: ["maitri-remove-dev-env", "java"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Java?" },
          },
          {
            type: "cmd",
            id: "rm-dev-dotnet",
            title: ".NET",
            icon: "hexagon",
            exec: ["maitri-remove-dev-env", "dotnet"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove .NET?" },
          },
          {
            type: "cmd",
            id: "rm-dev-ocaml",
            title: "OCaml",
            icon: "code-block",
            exec: ["maitri-remove-dev-env", "ocaml"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove OCaml?" },
          },
          {
            type: "cmd",
            id: "rm-dev-clojure",
            title: "Clojure",
            icon: "code-block",
            exec: ["maitri-remove-dev-env", "clojure"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Clojure?" },
          },
          {
            type: "cmd",
            id: "rm-dev-scala",
            title: "Scala",
            icon: "code-block",
            exec: ["maitri-remove-dev-env", "scala"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Scala?" },
          },
        ],
      },
      {
        type: "cmd",
        id: "rm-theme",
        title: "Theme",
        icon: "palette",
        exec: ["maitri-theme-remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Theme?" },
      },
      {
        type: "group",
        id: "rm-browser",
        title: "Browser",
        icon: "browser",
        children: [
          {
            type: "cmd",
            id: "rm-browser-chrome",
            title: "Chrome",
            icon: "google-chrome-logo",
            exec: ["maitri-remove-browser", "chrome"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Chrome?" },
          },
          {
            type: "cmd",
            id: "rm-browser-edge",
            title: "Edge",
            icon: "compass",
            exec: ["maitri-remove-browser", "edge"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Edge?" },
          },
          {
            type: "cmd",
            id: "rm-browser-brave",
            title: "Brave",
            icon: "browser",
            exec: ["maitri-remove-browser", "brave"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Brave?" },
          },
          {
            type: "cmd",
            id: "rm-browser-brave-origin",
            title: "Brave Origin",
            icon: "browser",
            exec: ["maitri-remove-browser", "brave-origin"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Brave Origin?" },
          },
          {
            type: "cmd",
            id: "rm-browser-firefox",
            title: "Firefox",
            icon: "compass",
            exec: ["maitri-remove-browser", "firefox"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Firefox?" },
          },
          {
            type: "cmd",
            id: "rm-browser-zen",
            title: "Zen",
            icon: "browser",
            exec: ["maitri-remove-browser", "zen"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Zen?" },
          },
        ],
      },
      {
        type: "cmd",
        id: "rm-dictation",
        title: "Dictation",
        icon: "microphone",
        exec: ["maitri-voxtype-remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Dictation?" },
      },
      {
        type: "group",
        id: "rm-gaming",
        title: "Gaming",
        icon: "game-controller",
        children: [
          {
            type: "cmd",
            id: "rm-gaming-steam",
            title: "Steam",
            icon: "steam-logo",
            exec: ["maitri-remove-gaming-steam"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Steam?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-retroarch",
            title: "RetroArch",
            icon: "joystick",
            exec: ["maitri-remove-gaming-retroarch"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove RetroArch?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-minecraft",
            title: "Minecraft",
            icon: "cube",
            exec: ["maitri-remove-gaming-minecraft"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Minecraft?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-geforce-now",
            title: "NVIDIA GeForce NOW",
            icon: "cloud",
            exec: ["maitri-remove-gaming-geforce-now"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove NVIDIA GeForce NOW?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-xbox-cloud",
            title: "Xbox Cloud Gaming",
            icon: "cloud",
            exec: ["maitri-remove-gaming-xbox-cloud"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Xbox Cloud Gaming?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-xbox-controller",
            title: "Xbox Controller",
            icon: "game-controller",
            exec: ["maitri-remove-gaming-xbox-controllers"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Xbox Controller?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-moonlight",
            title: "Moonlight (GameStream)",
            icon: "monitor",
            exec: ["maitri-remove-gaming-moonlight"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Moonlight?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-lutris",
            title: "Lutris (Battle.net)",
            icon: "joystick",
            exec: ["maitri-remove-gaming-lutris"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Lutris?" },
          },
          {
            type: "cmd",
            id: "rm-gaming-heroic",
            title: "Heroic (Epic Games)",
            icon: "game-controller",
            exec: ["maitri-remove-gaming-heroic"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Heroic?" },
          },
        ],
      },
      {
        type: "cmd",
        id: "rm-windows",
        title: "Windows",
        icon: "windows-logo",
        exec: ["maitri-windows-vm", "remove"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Windows?" },
      },
      {
        type: "cmd",
        id: "rm-preinstalls",
        title: "Preinstalls",
        icon: "app-window",
        exec: ["maitri-remove-preinstalls"],
        terminal: true,
        destructive: true,
        confirm: { title: "Remove Preinstalls?" },
      },
      {
        type: "group",
        id: "rm-security",
        title: "Security",
        icon: "shield-check",
        children: [
          {
            type: "cmd",
            id: "rm-security-fingerprint",
            title: "Fingerprint",
            icon: "fingerprint",
            exec: ["maitri-remove-security-fingerprint"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Fingerprint?" },
          },
          {
            type: "cmd",
            id: "rm-security-fido2",
            title: "Fido2",
            icon: "key",
            exec: ["maitri-remove-security-fido2"],
            terminal: true,
            destructive: true,
            confirm: { title: "Remove Fido2?" },
          },
        ],
      },
    ],
  },
];
